# Generated by Django 3.2 on 2021-05-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneAutocomplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(blank=True, max_length=255, null=True)),
                ('stable_id', models.CharField(max_length=128)),
                ('display_label', models.CharField(blank=True, max_length=128, null=True)),
                ('location', models.CharField(blank=True, max_length=60, null=True)),
                ('db', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'gene_autocomplete',
                'managed': False,
            },
        ),
    ]
